// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: clock.proto

package life3proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskEngine_GetClockState_FullMethodName    = "/life3.RiskEngine/GetClockState"
	RiskEngine_StreamClockState_FullMethodName = "/life3.RiskEngine/StreamClockState"
)

// RiskEngineClient is the client API for RiskEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskEngineClient interface {
	GetClockState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClockState, error)
	StreamClockState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClockState], error)
}

type riskEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskEngineClient(cc grpc.ClientConnInterface) RiskEngineClient {
	return &riskEngineClient{cc}
}

func (c *riskEngineClient) GetClockState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClockState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClockState)
	err := c.cc.Invoke(ctx, RiskEngine_GetClockState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskEngineClient) StreamClockState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClockState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RiskEngine_ServiceDesc.Streams[0], RiskEngine_StreamClockState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ClockState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RiskEngine_StreamClockStateClient = grpc.ServerStreamingClient[ClockState]

// RiskEngineServer is the server API for RiskEngine service.
// All implementations must embed UnimplementedRiskEngineServer
// for forward compatibility.
type RiskEngineServer interface {
	GetClockState(context.Context, *emptypb.Empty) (*ClockState, error)
	StreamClockState(*emptypb.Empty, grpc.ServerStreamingServer[ClockState]) error
	mustEmbedUnimplementedRiskEngineServer()
}

// UnimplementedRiskEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskEngineServer struct{}

func (UnimplementedRiskEngineServer) GetClockState(context.Context, *emptypb.Empty) (*ClockState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClockState not implemented")
}
func (UnimplementedRiskEngineServer) StreamClockState(*emptypb.Empty, grpc.ServerStreamingServer[ClockState]) error {
	return status.Errorf(codes.Unimplemented, "method StreamClockState not implemented")
}
func (UnimplementedRiskEngineServer) mustEmbedUnimplementedRiskEngineServer() {}
func (UnimplementedRiskEngineServer) testEmbeddedByValue()                    {}

// UnsafeRiskEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskEngineServer will
// result in compilation errors.
type UnsafeRiskEngineServer interface {
	mustEmbedUnimplementedRiskEngineServer()
}

func RegisterRiskEngineServer(s grpc.ServiceRegistrar, srv RiskEngineServer) {
	// If the following call pancis, it indicates UnimplementedRiskEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskEngine_ServiceDesc, srv)
}

func _RiskEngine_GetClockState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskEngineServer).GetClockState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskEngine_GetClockState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskEngineServer).GetClockState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskEngine_StreamClockState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RiskEngineServer).StreamClockState(m, &grpc.GenericServerStream[emptypb.Empty, ClockState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RiskEngine_StreamClockStateServer = grpc.ServerStreamingServer[ClockState]

// RiskEngine_ServiceDesc is the grpc.ServiceDesc for RiskEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "life3.RiskEngine",
	HandlerType: (*RiskEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClockState",
			Handler:    _RiskEngine_GetClockState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamClockState",
			Handler:       _RiskEngine_StreamClockState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clock.proto",
}
