// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: clock.proto

package life3proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClockState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MinutesToMidnight  float32                `protobuf:"fixed32,1,opt,name=minutes_to_midnight,json=minutesToMidnight,proto3" json:"minutes_to_midnight,omitempty"`
	DominantScenario   ScenarioID             `protobuf:"varint,2,opt,name=dominant_scenario,json=dominantScenario,proto3,enum=life3.ScenarioID" json:"dominant_scenario,omitempty"`
	ScenarioConfidence float32                `protobuf:"fixed32,3,opt,name=scenario_confidence,json=scenarioConfidence,proto3" json:"scenario_confidence,omitempty"`
	ScenarioWeights    []float32              `protobuf:"fixed32,4,rep,packed,name=scenario_weights,json=scenarioWeights,proto3" json:"scenario_weights,omitempty"`
	Sigma              float32                `protobuf:"fixed32,5,opt,name=sigma,proto3" json:"sigma,omitempty"`
	ComputedAt         int64                  `protobuf:"varint,6,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClockState) Reset() {
	*x = ClockState{}
	mi := &file_clock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockState) ProtoMessage() {}

func (x *ClockState) ProtoReflect() protoreflect.Message {
	mi := &file_clock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockState.ProtoReflect.Descriptor instead.
func (*ClockState) Descriptor() ([]byte, []int) {
	return file_clock_proto_rawDescGZIP(), []int{0}
}

func (x *ClockState) GetMinutesToMidnight() float32 {
	if x != nil {
		return x.MinutesToMidnight
	}
	return 0
}

func (x *ClockState) GetDominantScenario() ScenarioID {
	if x != nil {
		return x.DominantScenario
	}
	return ScenarioID_UNKNOWN
}

func (x *ClockState) GetScenarioConfidence() float32 {
	if x != nil {
		return x.ScenarioConfidence
	}
	return 0
}

func (x *ClockState) GetScenarioWeights() []float32 {
	if x != nil {
		return x.ScenarioWeights
	}
	return nil
}

func (x *ClockState) GetSigma() float32 {
	if x != nil {
		return x.Sigma
	}
	return 0
}

func (x *ClockState) GetComputedAt() int64 {
	if x != nil {
		return x.ComputedAt
	}
	return 0
}

var File_clock_proto protoreflect.FileDescriptor

const file_clock_proto_rawDesc = "" +
	"\n" +
	"\vclock.proto\x12\x05life3\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0escenario.proto\"\x8f\x02\n" +
	"\n" +
	"ClockState\x12.\n" +
	"\x13minutes_to_midnight\x18\x01 \x01(\x02R\x11minutesToMidnight\x12>\n" +
	"\x11dominant_scenario\x18\x02 \x01(\x0e2\x11.life3.ScenarioIDR\x10dominantScenario\x12/\n" +
	"\x13scenario_confidence\x18\x03 \x01(\x02R\x12scenarioConfidence\x12)\n" +
	"\x10scenario_weights\x18\x04 \x03(\x02R\x0fscenarioWeights\x12\x14\n" +
	"\x05sigma\x18\x05 \x01(\x02R\x05sigma\x12\x1f\n" +
	"\vcomputed_at\x18\x06 \x01(\x03R\n" +
	"computedAt2\x89\x01\n" +
	"\n" +
	"RiskEngine\x12:\n" +
	"\rGetClockState\x12\x16.google.protobuf.Empty\x1a\x11.life3.ClockState\x12?\n" +
	"\x10StreamClockState\x12\x16.google.protobuf.Empty\x1a\x11.life3.ClockState0\x01B#Z!github.com/life3/proto;life3protob\x06proto3"

var (
	file_clock_proto_rawDescOnce sync.Once
	file_clock_proto_rawDescData []byte
)

func file_clock_proto_rawDescGZIP() []byte {
	file_clock_proto_rawDescOnce.Do(func() {
		file_clock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clock_proto_rawDesc), len(file_clock_proto_rawDesc)))
	})
	return file_clock_proto_rawDescData
}

var file_clock_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clock_proto_goTypes = []any{
	(*ClockState)(nil),    // 0: life3.ClockState
	(ScenarioID)(0),       // 1: life3.ScenarioID
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_clock_proto_depIdxs = []int32{
	1, // 0: life3.ClockState.dominant_scenario:type_name -> life3.ScenarioID
	2, // 1: life3.RiskEngine.GetClockState:input_type -> google.protobuf.Empty
	2, // 2: life3.RiskEngine.StreamClockState:input_type -> google.protobuf.Empty
	0, // 3: life3.RiskEngine.GetClockState:output_type -> life3.ClockState
	0, // 4: life3.RiskEngine.StreamClockState:output_type -> life3.ClockState
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clock_proto_init() }
func file_clock_proto_init() {
	if File_clock_proto != nil {
		return
	}
	file_scenario_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clock_proto_rawDesc), len(file_clock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clock_proto_goTypes,
		DependencyIndexes: file_clock_proto_depIdxs,
		MessageInfos:      file_clock_proto_msgTypes,
	}.Build()
	File_clock_proto = out.File
	file_clock_proto_goTypes = nil
	file_clock_proto_depIdxs = nil
}
