// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: entropy.proto

package life3proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntropyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumBits       int32                  `protobuf:"varint,1,opt,name=num_bits,json=numBits,proto3" json:"num_bits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntropyRequest) Reset() {
	*x = EntropyRequest{}
	mi := &file_entropy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntropyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntropyRequest) ProtoMessage() {}

func (x *EntropyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entropy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntropyRequest.ProtoReflect.Descriptor instead.
func (*EntropyRequest) Descriptor() ([]byte, []int) {
	return file_entropy_proto_rawDescGZIP(), []int{0}
}

func (x *EntropyRequest) GetNumBits() int32 {
	if x != nil {
		return x.NumBits
	}
	return 0
}

type EntropyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bits          []bool                 `protobuf:"varint,1,rep,packed,name=bits,proto3" json:"bits,omitempty"`
	Delta         float32                `protobuf:"fixed32,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntropyResponse) Reset() {
	*x = EntropyResponse{}
	mi := &file_entropy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntropyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntropyResponse) ProtoMessage() {}

func (x *EntropyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entropy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntropyResponse.ProtoReflect.Descriptor instead.
func (*EntropyResponse) Descriptor() ([]byte, []int) {
	return file_entropy_proto_rawDescGZIP(), []int{1}
}

func (x *EntropyResponse) GetBits() []bool {
	if x != nil {
		return x.Bits
	}
	return nil
}

func (x *EntropyResponse) GetDelta() float32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

var File_entropy_proto protoreflect.FileDescriptor

const file_entropy_proto_rawDesc = "" +
	"\n" +
	"\rentropy.proto\x12\x05life3\"+\n" +
	"\x0eEntropyRequest\x12\x19\n" +
	"\bnum_bits\x18\x01 \x01(\x05R\anumBits\";\n" +
	"\x0fEntropyResponse\x12\x12\n" +
	"\x04bits\x18\x01 \x03(\bR\x04bits\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x02R\x05delta2M\n" +
	"\x0eEntropyService\x12;\n" +
	"\n" +
	"GetEntropy\x12\x15.life3.EntropyRequest\x1a\x16.life3.EntropyResponseB#Z!github.com/life3/proto;life3protob\x06proto3"

var (
	file_entropy_proto_rawDescOnce sync.Once
	file_entropy_proto_rawDescData []byte
)

func file_entropy_proto_rawDescGZIP() []byte {
	file_entropy_proto_rawDescOnce.Do(func() {
		file_entropy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entropy_proto_rawDesc), len(file_entropy_proto_rawDesc)))
	})
	return file_entropy_proto_rawDescData
}

var file_entropy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_entropy_proto_goTypes = []any{
	(*EntropyRequest)(nil),  // 0: life3.EntropyRequest
	(*EntropyResponse)(nil), // 1: life3.EntropyResponse
}
var file_entropy_proto_depIdxs = []int32{
	0, // 0: life3.EntropyService.GetEntropy:input_type -> life3.EntropyRequest
	1, // 1: life3.EntropyService.GetEntropy:output_type -> life3.EntropyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entropy_proto_init() }
func file_entropy_proto_init() {
	if File_entropy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entropy_proto_rawDesc), len(file_entropy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entropy_proto_goTypes,
		DependencyIndexes: file_entropy_proto_depIdxs,
		MessageInfos:      file_entropy_proto_msgTypes,
	}.Build()
	File_entropy_proto = out.File
	file_entropy_proto_goTypes = nil
	file_entropy_proto_depIdxs = nil
}
