// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: scenario.proto

package life3proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScenarioID int32

const (
	ScenarioID_UNKNOWN              ScenarioID = 0
	ScenarioID_LIBERTARIAN_UTOPIA   ScenarioID = 1
	ScenarioID_BENEVOLENT_DICTATOR  ScenarioID = 2
	ScenarioID_EGALITARIAN_UTOPIA   ScenarioID = 3
	ScenarioID_GATEKEEPER           ScenarioID = 4
	ScenarioID_PROTECTOR_GOD        ScenarioID = 5
	ScenarioID_ENSLAVED_GOD         ScenarioID = 6
	ScenarioID_CONQUERORS           ScenarioID = 7
	ScenarioID_DESCENDANTS          ScenarioID = 8
	ScenarioID_ZOOKEEPER            ScenarioID = 9
	ScenarioID_NINETEEN_EIGHTY_FOUR ScenarioID = 10
	ScenarioID_REVERT               ScenarioID = 11
	ScenarioID_SELF_DESTRUCTION     ScenarioID = 12
)

// Enum value maps for ScenarioID.
var (
	ScenarioID_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "LIBERTARIAN_UTOPIA",
		2:  "BENEVOLENT_DICTATOR",
		3:  "EGALITARIAN_UTOPIA",
		4:  "GATEKEEPER",
		5:  "PROTECTOR_GOD",
		6:  "ENSLAVED_GOD",
		7:  "CONQUERORS",
		8:  "DESCENDANTS",
		9:  "ZOOKEEPER",
		10: "NINETEEN_EIGHTY_FOUR",
		11: "REVERT",
		12: "SELF_DESTRUCTION",
	}
	ScenarioID_value = map[string]int32{
		"UNKNOWN":              0,
		"LIBERTARIAN_UTOPIA":   1,
		"BENEVOLENT_DICTATOR":  2,
		"EGALITARIAN_UTOPIA":   3,
		"GATEKEEPER":           4,
		"PROTECTOR_GOD":        5,
		"ENSLAVED_GOD":         6,
		"CONQUERORS":           7,
		"DESCENDANTS":          8,
		"ZOOKEEPER":            9,
		"NINETEEN_EIGHTY_FOUR": 10,
		"REVERT":               11,
		"SELF_DESTRUCTION":     12,
	}
)

func (x ScenarioID) Enum() *ScenarioID {
	p := new(ScenarioID)
	*p = x
	return p
}

func (x ScenarioID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScenarioID) Descriptor() protoreflect.EnumDescriptor {
	return file_scenario_proto_enumTypes[0].Descriptor()
}

func (ScenarioID) Type() protoreflect.EnumType {
	return &file_scenario_proto_enumTypes[0]
}

func (x ScenarioID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScenarioID.Descriptor instead.
func (ScenarioID) EnumDescriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{0}
}

type ScenarioSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      ScenarioID             `protobuf:"varint,1,opt,name=scenario,proto3,enum=life3.ScenarioID" json:"scenario,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,3,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioSignal) Reset() {
	*x = ScenarioSignal{}
	mi := &file_scenario_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioSignal) ProtoMessage() {}

func (x *ScenarioSignal) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioSignal.ProtoReflect.Descriptor instead.
func (*ScenarioSignal) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{0}
}

func (x *ScenarioSignal) GetScenario() ScenarioID {
	if x != nil {
		return x.Scenario
	}
	return ScenarioID_UNKNOWN
}

func (x *ScenarioSignal) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ScenarioSignal) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *ScenarioSignal) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ScenarioAggregate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weights       []float32              `protobuf:"fixed32,1,rep,packed,name=weights,proto3" json:"weights,omitempty"` // length 13, index = ScenarioID
	ComputedAt    int64                  `protobuf:"varint,2,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioAggregate) Reset() {
	*x = ScenarioAggregate{}
	mi := &file_scenario_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioAggregate) ProtoMessage() {}

func (x *ScenarioAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioAggregate.ProtoReflect.Descriptor instead.
func (*ScenarioAggregate) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{1}
}

func (x *ScenarioAggregate) GetWeights() []float32 {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *ScenarioAggregate) GetComputedAt() int64 {
	if x != nil {
		return x.ComputedAt
	}
	return 0
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_scenario_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{2}
}

func (x *SignalRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*ScenarioSignal      `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_scenario_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{3}
}

func (x *SignalResponse) GetSignals() []*ScenarioSignal {
	if x != nil {
		return x.Signals
	}
	return nil
}

type AggregateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowDays    int32                  `protobuf:"varint,1,opt,name=window_days,json=windowDays,proto3" json:"window_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateRequest) Reset() {
	*x = AggregateRequest{}
	mi := &file_scenario_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRequest) ProtoMessage() {}

func (x *AggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRequest.ProtoReflect.Descriptor instead.
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{4}
}

func (x *AggregateRequest) GetWindowDays() int32 {
	if x != nil {
		return x.WindowDays
	}
	return 0
}

var File_scenario_proto protoreflect.FileDescriptor

const file_scenario_proto_rawDesc = "" +
	"\n" +
	"\x0escenario.proto\x12\x05life3\"\x9c\x01\n" +
	"\x0eScenarioSignal\x12-\n" +
	"\bscenario\x18\x01 \x01(\x0e2\x11.life3.ScenarioIDR\bscenario\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"source_url\x18\x03 \x01(\tR\tsourceUrl\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"N\n" +
	"\x11ScenarioAggregate\x12\x18\n" +
	"\aweights\x18\x01 \x03(\x02R\aweights\x12\x1f\n" +
	"\vcomputed_at\x18\x02 \x01(\x03R\n" +
	"computedAt\"%\n" +
	"\rSignalRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"A\n" +
	"\x0eSignalResponse\x12/\n" +
	"\asignals\x18\x01 \x03(\v2\x15.life3.ScenarioSignalR\asignals\"3\n" +
	"\x10AggregateRequest\x12\x1f\n" +
	"\vwindow_days\x18\x01 \x01(\x05R\n" +
	"windowDays*\x83\x02\n" +
	"\n" +
	"ScenarioID\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x16\n" +
	"\x12LIBERTARIAN_UTOPIA\x10\x01\x12\x17\n" +
	"\x13BENEVOLENT_DICTATOR\x10\x02\x12\x16\n" +
	"\x12EGALITARIAN_UTOPIA\x10\x03\x12\x0e\n" +
	"\n" +
	"GATEKEEPER\x10\x04\x12\x11\n" +
	"\rPROTECTOR_GOD\x10\x05\x12\x10\n" +
	"\fENSLAVED_GOD\x10\x06\x12\x0e\n" +
	"\n" +
	"CONQUERORS\x10\a\x12\x0f\n" +
	"\vDESCENDANTS\x10\b\x12\r\n" +
	"\tZOOKEEPER\x10\t\x12\x18\n" +
	"\x14NINETEEN_EIGHTY_FOUR\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06REVERT\x10\v\x12\x14\n" +
	"\x10SELF_DESTRUCTION\x10\f2\xd9\x01\n" +
	"\x13IntelligenceService\x12?\n" +
	"\x10GetLatestSignals\x12\x14.life3.SignalRequest\x1a\x15.life3.SignalResponse\x12A\n" +
	"\fGetAggregate\x12\x17.life3.AggregateRequest\x1a\x18.life3.ScenarioAggregate\x12>\n" +
	"\rStreamSignals\x12\x14.life3.SignalRequest\x1a\x15.life3.ScenarioSignal0\x01B#Z!github.com/life3/proto;life3protob\x06proto3"

var (
	file_scenario_proto_rawDescOnce sync.Once
	file_scenario_proto_rawDescData []byte
)

func file_scenario_proto_rawDescGZIP() []byte {
	file_scenario_proto_rawDescOnce.Do(func() {
		file_scenario_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scenario_proto_rawDesc), len(file_scenario_proto_rawDesc)))
	})
	return file_scenario_proto_rawDescData
}

var file_scenario_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scenario_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_scenario_proto_goTypes = []any{
	(ScenarioID)(0),           // 0: life3.ScenarioID
	(*ScenarioSignal)(nil),    // 1: life3.ScenarioSignal
	(*ScenarioAggregate)(nil), // 2: life3.ScenarioAggregate
	(*SignalRequest)(nil),     // 3: life3.SignalRequest
	(*SignalResponse)(nil),    // 4: life3.SignalResponse
	(*AggregateRequest)(nil),  // 5: life3.AggregateRequest
}
var file_scenario_proto_depIdxs = []int32{
	0, // 0: life3.ScenarioSignal.scenario:type_name -> life3.ScenarioID
	1, // 1: life3.SignalResponse.signals:type_name -> life3.ScenarioSignal
	3, // 2: life3.IntelligenceService.GetLatestSignals:input_type -> life3.SignalRequest
	5, // 3: life3.IntelligenceService.GetAggregate:input_type -> life3.AggregateRequest
	3, // 4: life3.IntelligenceService.StreamSignals:input_type -> life3.SignalRequest
	4, // 5: life3.IntelligenceService.GetLatestSignals:output_type -> life3.SignalResponse
	2, // 6: life3.IntelligenceService.GetAggregate:output_type -> life3.ScenarioAggregate
	1, // 7: life3.IntelligenceService.StreamSignals:output_type -> life3.ScenarioSignal
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scenario_proto_init() }
func file_scenario_proto_init() {
	if File_scenario_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scenario_proto_rawDesc), len(file_scenario_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scenario_proto_goTypes,
		DependencyIndexes: file_scenario_proto_depIdxs,
		EnumInfos:         file_scenario_proto_enumTypes,
		MessageInfos:      file_scenario_proto_msgTypes,
	}.Build()
	File_scenario_proto = out.File
	file_scenario_proto_goTypes = nil
	file_scenario_proto_depIdxs = nil
}
