// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: scenario.proto

package life3proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntelligenceService_GetLatestSignals_FullMethodName = "/life3.IntelligenceService/GetLatestSignals"
	IntelligenceService_GetAggregate_FullMethodName     = "/life3.IntelligenceService/GetAggregate"
	IntelligenceService_StreamSignals_FullMethodName    = "/life3.IntelligenceService/StreamSignals"
)

// IntelligenceServiceClient is the client API for IntelligenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntelligenceServiceClient interface {
	GetLatestSignals(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	GetAggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*ScenarioAggregate, error)
	StreamSignals(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScenarioSignal], error)
}

type intelligenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntelligenceServiceClient(cc grpc.ClientConnInterface) IntelligenceServiceClient {
	return &intelligenceServiceClient{cc}
}

func (c *intelligenceServiceClient) GetLatestSignals(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_GetLatestSignals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) GetAggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*ScenarioAggregate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScenarioAggregate)
	err := c.cc.Invoke(ctx, IntelligenceService_GetAggregate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) StreamSignals(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScenarioSignal], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IntelligenceService_ServiceDesc.Streams[0], IntelligenceService_StreamSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SignalRequest, ScenarioSignal]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntelligenceService_StreamSignalsClient = grpc.ServerStreamingClient[ScenarioSignal]

// IntelligenceServiceServer is the server API for IntelligenceService service.
// All implementations must embed UnimplementedIntelligenceServiceServer
// for forward compatibility.
type IntelligenceServiceServer interface {
	GetLatestSignals(context.Context, *SignalRequest) (*SignalResponse, error)
	GetAggregate(context.Context, *AggregateRequest) (*ScenarioAggregate, error)
	StreamSignals(*SignalRequest, grpc.ServerStreamingServer[ScenarioSignal]) error
	mustEmbedUnimplementedIntelligenceServiceServer()
}

// UnimplementedIntelligenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntelligenceServiceServer struct{}

func (UnimplementedIntelligenceServiceServer) GetLatestSignals(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestSignals not implemented")
}
func (UnimplementedIntelligenceServiceServer) GetAggregate(context.Context, *AggregateRequest) (*ScenarioAggregate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAggregate not implemented")
}
func (UnimplementedIntelligenceServiceServer) StreamSignals(*SignalRequest, grpc.ServerStreamingServer[ScenarioSignal]) error {
	return status.Errorf(codes.Unimplemented, "method StreamSignals not implemented")
}
func (UnimplementedIntelligenceServiceServer) mustEmbedUnimplementedIntelligenceServiceServer() {}
func (UnimplementedIntelligenceServiceServer) testEmbeddedByValue()                             {}

// UnsafeIntelligenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntelligenceServiceServer will
// result in compilation errors.
type UnsafeIntelligenceServiceServer interface {
	mustEmbedUnimplementedIntelligenceServiceServer()
}

func RegisterIntelligenceServiceServer(s grpc.ServiceRegistrar, srv IntelligenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedIntelligenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntelligenceService_ServiceDesc, srv)
}

func _IntelligenceService_GetLatestSignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).GetLatestSignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_GetLatestSignals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).GetLatestSignals(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_GetAggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).GetAggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_GetAggregate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).GetAggregate(ctx, req.(*AggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_StreamSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SignalRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IntelligenceServiceServer).StreamSignals(m, &grpc.GenericServerStream[SignalRequest, ScenarioSignal]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntelligenceService_StreamSignalsServer = grpc.ServerStreamingServer[ScenarioSignal]

// IntelligenceService_ServiceDesc is the grpc.ServiceDesc for IntelligenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntelligenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "life3.IntelligenceService",
	HandlerType: (*IntelligenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestSignals",
			Handler:    _IntelligenceService_GetLatestSignals_Handler,
		},
		{
			MethodName: "GetAggregate",
			Handler:    _IntelligenceService_GetAggregate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSignals",
			Handler:       _IntelligenceService_StreamSignals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scenario.proto",
}
