fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Proto stubs will be generated by shared/scripts/gen_proto.sh.
    // Uncomment once shared/proto/*.proto files exist:
    // tonic_build::configure()
    //     .build_server(true)
    //     .compile(
    //         &["../../shared/proto/clock.proto", "../../shared/proto/scenario.proto"],
    //         &["../../shared/proto"],
    //     )?;
    Ok(())
}
